# Generated by Django 3.0.2 on 2020-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=50)),
                ('car_owner', models.CharField(max_length=200)),
                ('car_color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=8)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
