# Generated by Django 3.0.2 on 2020-02-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarType',
            new_name='Car',
        ),
    ]
